name: Contributors

on:
  push:
    branches: "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: akhilmhdh/contributors-readme-action@v2.3.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
